set $mod Mod4
set $left h
set $down j
set $up k
set $right l

set $term kitty

set $menu wofi --show drun

set $run wofi --show run

set $drun-rofi rofi -show drun

set $run-rofi rofi -show run

set $file nautilus

# wallpaper
output * bg /home/vshark/Pictures/walls/clouds-5.jpg fill

# gaps
gaps outer 2px
gaps inner 10px

# get rid of titlebars
font pango:monospace 0.001
titlebar_padding 1
titlebar_border_thickness 0

# border size
for_window [class="^.*"] border pixel 2

# border color
# --------------------- - border -- bg --- text -- ind - ch_border
#client.focused           #8087a2 #181926 #cad3f5 #f4dbd6 #8087a2
#client.focused_inactive  #1e2030 #1e2030 #cad3f5 #939ab7 #8087a2
#client.unfocused         #1e2030 #1e2030 #cad3f5 #8087a2 #8087a2
#client.urgent            #1e2030 #181926 #cad3f5 #ee99a0 #8087a2
#client.placeholder       #1e2030 #181926 #cad3f5 #ed8796 #8087a2

#                       border    bg      text    ind   child border
client.focused          #b7bdf8 #141216 #d8cab8 #b7bdf8 #b7bdf8
client.focused_inactive #6e738d #b7bdf8 #d8cab8 #6e738d #6e738d
client.unfocused        #6e738d #b7bdf8 #d8cab8 #181926 #6e738d
client.urgent           #fcb167 #141216 #d8cab8 #fcb167 #fcb167
client.placeholder      #AC82E9 #141216 #d8cab8 #AC82E9 #AC82E9

# round windows corners
corner_radius 10

# shadows
shadows enable

# misc
scratchpad_minimize enable
titlebar_separator disable