set $mod Mod4
set $left h
set $down j
set $up k
set $right l

set $term kitty

set $menu wofi --show drun

set $run wofi --show run

set $drun-rofi rofi -show drun

set $run-rofi rofi -show run

set $file nautilus

# automatically assign windows to their workspaces
assign [class="Floorp"] workspace 1:󰖟
assign [class="Helium Browser"] workspace 1:󰖟
assign [class="kitty"] workspace 2:
assign [class="Visual Studio Code"] workspace 3:󰅴
assign [class="VSCodium"] workspace 3:󰅴
assign [class="Feishin"] workspace 4:
assign [class="Spotify"] workspace 4:
assign [class="Spotify Premium"] workspace 4:
assign [class="Telegram"] workspace 5:󰍡
assign [class="Discord"] workspace 5:󰍡
assign [class="Vesktop"] workspace 5:󰍡
assign [class="Element"] workspace 5:󰍡
assign [class="FluffyChat"] workspace 5:󰍡
assign [class="Steam"] workspace 6:󰊖
assign [class="Lutris"] workspace 6:󰊖
assign [class="Modrinth App"] workspace 6:󰊖
assign [class="Modrinth"] workspace 6:󰊖
assign [class="Sober"] workspace 6:󰊖
assign [class="PekoraPlayerBootstrapper"] workspace 6:󰊖
assign [class="Roblox"] workspace 6:󰊖
assign [class="OBS Studio"] workspace 7:
assign [class="Files"] workspace 8:󰉋

# switch to a workspace
bindsym $mod+1 workspace number 1:󰖟
bindsym $mod+2 workspace number 2:
bindsym $mod+3 workspace number 3:󰅴
bindsym $mod+4 workspace number 4:
bindsym $mod+5 workspace number 5:󰍡
bindsym $mod+6 workspace number 6:󰊖
bindsym $mod+7 workspace number 7:
bindsym $mod+8 workspace number 8:󰉋
bindsym $mod+9 workspace number 9:󰇘
bindsym $mod+0 workspace number 10:󰇘

# move focused window to another workspace
bindsym $mod+Shift+1 move container to workspace number 1:󰖟
bindsym $mod+Shift+2 move container to workspace number 2:
bindsym $mod+Shift+3 move container to workspace number 3:󰅴
bindsym $mod+Shift+4 move container to workspace number 4:
bindsym $mod+Shift+5 move container to workspace number 5:󰍡
bindsym $mod+Shift+6 move container to workspace number 6:󰊖
bindsym $mod+Shift+7 move container to workspace number 7:
bindsym $mod+Shift+8 move container to workspace number 8:󰉋
bindsym $mod+Shift+9 move container to workspace number 9:󰇘
bindsym $mod+Shift+0 move container to workspace number 10:󰇘